name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Use actions/checkout@v3 for repo checkout
        with:
          fetch-depth: 0  # Ensures the full history is fetched

      - uses: actions/setup-node@v3  # Use actions/setup-node@v3 for Node.js setup
        with:
          node-version: '18'  # Set Node.js version

      - name: Cache yarn dependencies
        uses: actions/cache@v3  # Use actions/cache@v3 (latest stable version)
        with:
          path: ~/.yarn/cache  # Define the path to the yarn cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}  # Cache key using yarn.lock hash
          restore-keys: |
            ${{ runner.os }}-yarn-  # If the exact key is not found, restore the key starting with OS and yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile  # Install dependencies using yarn

      - name: Build website
        run: yarn build  # Build the Docusaurus website

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3  # Use actions/upload-artifact@v3 for uploading build artifact
        with:
          path: build  # Upload the build directory

  deploy:
    name: Deploy to GitHub Pages
    needs: build  # Ensure the build job runs before deploy
    runs-on: ubuntu-latest

    permissions:
      pages: write  # Grant write access to Pages for deployment
      id-token: write  # Access to generate an ID token for authentication

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  # Use actions/deploy-pages@v4 (latest stable version)
        with:
          branch: gh-pages  # Deploy to the gh-pages branch for GitHub Pages
